/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package appperpus;

import java.awt.Color;

/**
 *
 * @author mac
 */
public class Mainmenu_Admin extends javax.swing.JFrame {

    /**
     * Creates new form Mainmenu_dashboard
     */
    public Mainmenu_Admin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Pn_menu = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Btn_dashboard = new javax.swing.JButton();
        Btn_dashboard1 = new javax.swing.JButton();
        Btn_dashboard2 = new javax.swing.JButton();
        Btn_dashboard3 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        Btn_dashboard4 = new javax.swing.JButton();
        Btn_dashboard5 = new javax.swing.JButton();
        Pn_tampil = new javax.swing.JPanel();
        Navbar = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        Panel_utama = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Pn_menu.setBackground(new java.awt.Color(102, 51, 0));
        Pn_menu.setPreferredSize(new java.awt.Dimension(200, 600));

        jLabel1.setFont(new java.awt.Font("PT Sans Caption", 1, 10)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 204, 51));
        jLabel1.setText("Perpustakaan");

        jLabel2.setFont(new java.awt.Font("PT Sans Caption", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 204, 51));
        jLabel2.setText("Aksara Maya");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/LOGO 2.png"))); // NOI18N

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Admin");

        Btn_dashboard.setFont(new java.awt.Font("Didot", 1, 13)); // NOI18N
        Btn_dashboard.setText("Dashboard");
        Btn_dashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Btn_dashboardMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Btn_dashboardMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Btn_dashboardMouseExited(evt);
            }
        });

        Btn_dashboard1.setFont(new java.awt.Font("Didot", 1, 12)); // NOI18N
        Btn_dashboard1.setText("Manajemen Buku Asli");
        Btn_dashboard1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Btn_dashboard1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Btn_dashboard1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Btn_dashboard1MouseExited(evt);
            }
        });

        Btn_dashboard2.setFont(new java.awt.Font("Didot", 1, 13)); // NOI18N
        Btn_dashboard2.setText("Manajemen Anggota");
        Btn_dashboard2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Btn_dashboard2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Btn_dashboard2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Btn_dashboard2MouseExited(evt);
            }
        });

        Btn_dashboard3.setFont(new java.awt.Font("Didot", 1, 12)); // NOI18N
        Btn_dashboard3.setText("Manajemen Buku Online");
        Btn_dashboard3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Btn_dashboard3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Btn_dashboard3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Btn_dashboard3MouseExited(evt);
            }
        });
        Btn_dashboard3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_dashboard3ActionPerformed(evt);
            }
        });

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Operasional");

        Btn_dashboard4.setFont(new java.awt.Font("Didot", 1, 13)); // NOI18N
        Btn_dashboard4.setText("Peminjaman");
        Btn_dashboard4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Btn_dashboard4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Btn_dashboard4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Btn_dashboard4MouseExited(evt);
            }
        });

        Btn_dashboard5.setFont(new java.awt.Font("Didot", 1, 13)); // NOI18N
        Btn_dashboard5.setText("Pengembalian");
        Btn_dashboard5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Btn_dashboard5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Btn_dashboard5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Btn_dashboard5MouseExited(evt);
            }
        });

        javax.swing.GroupLayout Pn_menuLayout = new javax.swing.GroupLayout(Pn_menu);
        Pn_menu.setLayout(Pn_menuLayout);
        Pn_menuLayout.setHorizontalGroup(
            Pn_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Pn_menuLayout.createSequentialGroup()
                .addGroup(Pn_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Pn_menuLayout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Pn_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)))
                    .addGroup(Pn_menuLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(Pn_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Btn_dashboard1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Btn_dashboard3, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Btn_dashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Btn_dashboard2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(Btn_dashboard4, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Btn_dashboard5, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        Pn_menuLayout.setVerticalGroup(
            Pn_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Pn_menuLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(Pn_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Pn_menuLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(1, 1, 1)
                        .addComponent(jLabel2))
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(Btn_dashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Btn_dashboard1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Btn_dashboard3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Btn_dashboard2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Btn_dashboard4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Btn_dashboard5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(305, Short.MAX_VALUE))
        );

        getContentPane().add(Pn_menu, java.awt.BorderLayout.LINE_START);

        Pn_tampil.setLayout(new java.awt.BorderLayout());

        Navbar.setBackground(new java.awt.Color(153, 102, 0));
        Navbar.setPreferredSize(new java.awt.Dimension(600, 50));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/petugas_white.png"))); // NOI18N
        jLabel7.setText("Admin");

        javax.swing.GroupLayout NavbarLayout = new javax.swing.GroupLayout(Navbar);
        Navbar.setLayout(NavbarLayout);
        NavbarLayout.setHorizontalGroup(
            NavbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NavbarLayout.createSequentialGroup()
                .addContainerGap(761, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(16, 16, 16))
        );
        NavbarLayout.setVerticalGroup(
            NavbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NavbarLayout.createSequentialGroup()
                .addContainerGap(11, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(15, 15, 15))
        );

        Pn_tampil.add(Navbar, java.awt.BorderLayout.PAGE_START);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        Panel_utama.setBackground(new java.awt.Color(255, 255, 255));
        Panel_utama.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(Panel_utama, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(Panel_utama, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );

        Pn_tampil.add(jPanel1, java.awt.BorderLayout.CENTER);

        getContentPane().add(Pn_tampil, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_dashboardMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_dashboardMouseEntered
        Btn_dashboard.setBackground(Color.gray);
        
    }//GEN-LAST:event_Btn_dashboardMouseEntered

    private void Btn_dashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_dashboardMouseClicked
        Panel_utama.removeAll();
        Panel_utama.add(new Panel_dashboard());
        Panel_utama.repaint();
        Panel_utama.revalidate();
    }//GEN-LAST:event_Btn_dashboardMouseClicked

    private void Btn_dashboardMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_dashboardMouseExited
        Btn_dashboard.setBackground(Color.white);
    }//GEN-LAST:event_Btn_dashboardMouseExited

    private void Btn_dashboard1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_dashboard1MouseClicked
        Panel_utama.removeAll();
        Panel_utama.add(new Panel_Buku());
        Panel_utama.repaint();
        Panel_utama.revalidate();
    }//GEN-LAST:event_Btn_dashboard1MouseClicked

    private void Btn_dashboard1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_dashboard1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_dashboard1MouseEntered

    private void Btn_dashboard1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_dashboard1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_dashboard1MouseExited

    private void Btn_dashboard2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_dashboard2MouseClicked
        Panel_utama.removeAll();
        Panel_utama.add(new Panel_Anggota());
        Panel_utama.repaint();
        Panel_utama.revalidate();
    }//GEN-LAST:event_Btn_dashboard2MouseClicked

    private void Btn_dashboard2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_dashboard2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_dashboard2MouseEntered

    private void Btn_dashboard2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_dashboard2MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_dashboard2MouseExited

    private void Btn_dashboard3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_dashboard3MouseClicked
        Panel_utama.removeAll();
        Panel_utama.add(new PanelAdmin_BukuOnline());
        Panel_utama.repaint();
        Panel_utama.revalidate();
    }//GEN-LAST:event_Btn_dashboard3MouseClicked

    private void Btn_dashboard3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_dashboard3MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_dashboard3MouseEntered

    private void Btn_dashboard3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_dashboard3MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_dashboard3MouseExited

    private void Btn_dashboard4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_dashboard4MouseClicked
        Panel_utama.removeAll();
        Panel_utama.add(new Panel_Peminjaman());
        Panel_utama.repaint();
        Panel_utama.revalidate();
    }//GEN-LAST:event_Btn_dashboard4MouseClicked

    private void Btn_dashboard4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_dashboard4MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_dashboard4MouseEntered

    private void Btn_dashboard4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_dashboard4MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_dashboard4MouseExited

    private void Btn_dashboard5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_dashboard5MouseClicked
        Panel_utama.removeAll();
        Panel_utama.add(new Panel_Pengembalian());
        Panel_utama.repaint();
        Panel_utama.revalidate();
    }//GEN-LAST:event_Btn_dashboard5MouseClicked

    private void Btn_dashboard5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_dashboard5MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_dashboard5MouseEntered

    private void Btn_dashboard5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_dashboard5MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_dashboard5MouseExited

    private void Btn_dashboard3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_dashboard3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_dashboard3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mainmenu_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mainmenu_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mainmenu_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mainmenu_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Mainmenu_Admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_dashboard;
    private javax.swing.JButton Btn_dashboard1;
    private javax.swing.JButton Btn_dashboard2;
    private javax.swing.JButton Btn_dashboard3;
    private javax.swing.JButton Btn_dashboard4;
    private javax.swing.JButton Btn_dashboard5;
    private javax.swing.JPanel Navbar;
    private javax.swing.JPanel Panel_utama;
    private javax.swing.JPanel Pn_menu;
    private javax.swing.JPanel Pn_tampil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
