/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package appperpus;

import java.awt.Color;
import appperpus.BlueprintAnggota;
import javax.swing.JOptionPane;
import appperpus.Panel_BukuUser; // <--- IMPOR PENTING DITAMBAHKAN DI SINI
import appperpus.Panel_profil; // Pastikan ini juga diimpor jika digunakan
import appperpus.Panel_bukuonline; // Pastikan ini juga diimpor jika digunakan
 // Pastikan ini juga diimpor jika digunakan



/**
 *
 * @author mac
 */
public class Mainmenu_User extends javax.swing.JFrame {
    private BlueprintAnggota loggedInAnggota;
    /**
     * Creates new form Mainmenu_dashboard
     */
    public Mainmenu_User(BlueprintAnggota anggota) {
        this.loggedInAnggota = anggota;
        initComponents();
        displayPanel(new Panel_BukuUser());
    }
    
    public Mainmenu_User() {
        initComponents();
        displayPanel(new Panel_BukuUser());
    }
    
    private void displayPanel(javax.swing.JPanel panelToDisplay) {
        Panel_user.removeAll(); // Hapus semua komponen yang ada
        Panel_user.setLayout(new java.awt.BorderLayout()); // Pastikan layout adalah BorderLayout
        Panel_user.add(panelToDisplay, java.awt.BorderLayout.CENTER); // Tambahkan panel baru
        Panel_user.revalidate(); // Validasi ulang layout
        Panel_user.repaint();    // Gambar ulang komponen
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Btn_dashboard5 = new javax.swing.JButton();
        Pn_menu = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Btn_ProfilAkun = new javax.swing.JButton();
        Btn_LihatDaftarBuku = new javax.swing.JButton();
        Btn_BacaBukuOnline = new javax.swing.JButton();
        Pn_tampil = new javax.swing.JPanel();
        Navbar = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        Panel_user = new javax.swing.JPanel();

        Btn_dashboard5.setFont(new java.awt.Font("Didot", 1, 13)); // NOI18N
        Btn_dashboard5.setText("Baca Buku Online");
        Btn_dashboard5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Btn_dashboard5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Btn_dashboard5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Btn_dashboard5MouseExited(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Pn_menu.setBackground(new java.awt.Color(102, 51, 0));
        Pn_menu.setPreferredSize(new java.awt.Dimension(200, 600));

        jLabel1.setFont(new java.awt.Font("PT Sans Caption", 1, 10)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 204, 51));
        jLabel1.setText("Perpustakaan");

        jLabel2.setFont(new java.awt.Font("PT Sans Caption", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 204, 51));
        jLabel2.setText("Aksara Maya");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/LOGO 2.png"))); // NOI18N

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Menu");

        Btn_ProfilAkun.setFont(new java.awt.Font("Didot", 1, 13)); // NOI18N
        Btn_ProfilAkun.setText("Profil");
        Btn_ProfilAkun.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Btn_ProfilAkunMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Btn_ProfilAkunMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Btn_ProfilAkunMouseExited(evt);
            }
        });

        Btn_LihatDaftarBuku.setFont(new java.awt.Font("Didot", 1, 12)); // NOI18N
        Btn_LihatDaftarBuku.setText("Lihat Daftar Buku");
        Btn_LihatDaftarBuku.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Btn_LihatDaftarBukuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Btn_LihatDaftarBukuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Btn_LihatDaftarBukuMouseExited(evt);
            }
        });

        Btn_BacaBukuOnline.setFont(new java.awt.Font("Didot", 1, 13)); // NOI18N
        Btn_BacaBukuOnline.setText("Baca Buku Online");
        Btn_BacaBukuOnline.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Btn_BacaBukuOnlineMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Btn_BacaBukuOnlineMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Btn_BacaBukuOnlineMouseExited(evt);
            }
        });

        javax.swing.GroupLayout Pn_menuLayout = new javax.swing.GroupLayout(Pn_menu);
        Pn_menu.setLayout(Pn_menuLayout);
        Pn_menuLayout.setHorizontalGroup(
            Pn_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Pn_menuLayout.createSequentialGroup()
                .addGroup(Pn_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Pn_menuLayout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Pn_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)))
                    .addGroup(Pn_menuLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(Pn_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Btn_LihatDaftarBuku, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Btn_ProfilAkun, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Btn_BacaBukuOnline, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        Pn_menuLayout.setVerticalGroup(
            Pn_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Pn_menuLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(Pn_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Pn_menuLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(1, 1, 1)
                        .addComponent(jLabel2))
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(Btn_ProfilAkun, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(Btn_LihatDaftarBuku, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(Btn_BacaBukuOnline, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(430, Short.MAX_VALUE))
        );

        getContentPane().add(Pn_menu, java.awt.BorderLayout.LINE_START);

        Pn_tampil.setLayout(new java.awt.BorderLayout());

        Navbar.setBackground(new java.awt.Color(153, 102, 0));
        Navbar.setPreferredSize(new java.awt.Dimension(600, 50));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/petugas_white.png"))); // NOI18N
        jLabel5.setText("User");

        javax.swing.GroupLayout NavbarLayout = new javax.swing.GroupLayout(Navbar);
        Navbar.setLayout(NavbarLayout);
        NavbarLayout.setHorizontalGroup(
            NavbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NavbarLayout.createSequentialGroup()
                .addContainerGap(771, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(18, 18, 18))
        );
        NavbarLayout.setVerticalGroup(
            NavbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NavbarLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel5)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        Pn_tampil.add(Navbar, java.awt.BorderLayout.PAGE_START);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        Panel_user.setBackground(new java.awt.Color(255, 255, 255));
        Panel_user.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(Panel_user, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(Panel_user, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        Pn_tampil.add(jPanel1, java.awt.BorderLayout.CENTER);

        getContentPane().add(Pn_tampil, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_ProfilAkunMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_ProfilAkunMouseEntered
        Btn_ProfilAkun.setBackground(Color.gray);
        
    }//GEN-LAST:event_Btn_ProfilAkunMouseEntered

    private void Btn_ProfilAkunMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_ProfilAkunMouseClicked
        if (loggedInAnggota != null) {
        // Pastikan Panel_user adalah container (misal: JPanel)
        Panel_user.removeAll(); // Hapus semua komponen yang mungkin ada sebelumnya
        Panel_user.setLayout(new java.awt.BorderLayout()); // Atur layout jika perlu
        Panel_user.add(new Panel_profil(loggedInAnggota), java.awt.BorderLayout.CENTER); // Tambahkan panel profil
        Panel_user.revalidate(); // Validasi ulang layout
        Panel_user.repaint();    // Gambar ulang komponen
    } else {
        JOptionPane.showMessageDialog(this, "Data anggota tidak tersedia. Silakan login kembali.", "Error", JOptionPane.ERROR_MESSAGE);
    }
        
    }//GEN-LAST:event_Btn_ProfilAkunMouseClicked

    private void Btn_ProfilAkunMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_ProfilAkunMouseExited
        Btn_ProfilAkun.setBackground(Color.white);
         if (loggedInAnggota != null) {
            // <--- Buat instance Panel_profil dan teruskan objek loggedInAnggota
            Panel_profil profilPanel = new Panel_profil(loggedInAnggota);
            //profilPanel.setVisible(true); // Tampilkan jendela profil
            // this.dispose(); // Anda mungkin ingin tetap membuka Mainmenu_User
        } else {
            JOptionPane.showMessageDialog(this, "Data profil tidak tersedia. Silakan login kembali.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    
    }//GEN-LAST:event_Btn_ProfilAkunMouseExited

    private void Btn_LihatDaftarBukuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_LihatDaftarBukuMouseClicked
        Panel_user.removeAll();
        Panel_user.add(new Panel_BukuUser());
        Panel_user.repaint();
        Panel_user.revalidate();
    }//GEN-LAST:event_Btn_LihatDaftarBukuMouseClicked

    private void Btn_LihatDaftarBukuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_LihatDaftarBukuMouseEntered
        Btn_LihatDaftarBuku.setBackground(Color.lightGray);
    }//GEN-LAST:event_Btn_LihatDaftarBukuMouseEntered

    private void Btn_LihatDaftarBukuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_LihatDaftarBukuMouseExited
        Btn_LihatDaftarBuku.setBackground(Color.white);
    }//GEN-LAST:event_Btn_LihatDaftarBukuMouseExited

    private void Btn_BacaBukuOnlineMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_BacaBukuOnlineMouseClicked
        Panel_user.removeAll();
        Panel_user.add(new Panel_bukuonline());
        Panel_user.repaint();
        Panel_user.revalidate();
        displayPanel(new Panel_bukuonline());
    }//GEN-LAST:event_Btn_BacaBukuOnlineMouseClicked

    private void Btn_BacaBukuOnlineMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_BacaBukuOnlineMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_BacaBukuOnlineMouseEntered

    private void Btn_BacaBukuOnlineMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_BacaBukuOnlineMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_BacaBukuOnlineMouseExited

    private void Btn_dashboard5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_dashboard5MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_dashboard5MouseClicked

    private void Btn_dashboard5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_dashboard5MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_dashboard5MouseEntered

    private void Btn_dashboard5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_dashboard5MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_dashboard5MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mainmenu_User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mainmenu_User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mainmenu_User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mainmenu_User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mainmenu_User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mainmenu_User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mainmenu_User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mainmenu_User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Mainmenu_User().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_BacaBukuOnline;
    private javax.swing.JButton Btn_LihatDaftarBuku;
    private javax.swing.JButton Btn_ProfilAkun;
    private javax.swing.JButton Btn_dashboard5;
    private javax.swing.JPanel Navbar;
    private javax.swing.JPanel Panel_user;
    private javax.swing.JPanel Pn_menu;
    private javax.swing.JPanel Pn_tampil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
