/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package appperpus;

/**
 *
 * @author mac
 */
public class Panel_dashboard extends javax.swing.JPanel {

    /**
     * Creates new form Panel_dashboard
     */
    public Panel_dashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        paneldasar = new javax.swing.JPanel();
        Cardanggota = new javax.swing.JPanel();
        Lb_nama = new javax.swing.JLabel();
        Lbl_icon = new javax.swing.JLabel();
        Lbl_jumlah = new javax.swing.JLabel();
        Cardbuku = new javax.swing.JPanel();
        Lb_nama1 = new javax.swing.JLabel();
        Lbl_icon1 = new javax.swing.JLabel();
        Lbl_jumlah1 = new javax.swing.JLabel();
        Cardpeminjam = new javax.swing.JPanel();
        Lb_nama2 = new javax.swing.JLabel();
        Lbl_icon2 = new javax.swing.JLabel();
        Lbl_jumlah2 = new javax.swing.JLabel();
        Cardpengembalian = new javax.swing.JPanel();
        Lb_nama3 = new javax.swing.JLabel();
        Lbl_icon3 = new javax.swing.JLabel();
        Lbl_jumlah3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.CardLayout());

        paneldasar.setBackground(new java.awt.Color(255, 255, 255));
        paneldasar.setPreferredSize(new java.awt.Dimension(70, 50));

        Cardanggota.setBackground(new java.awt.Color(102, 51, 0));

        Lb_nama.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        Lb_nama.setForeground(new java.awt.Color(255, 255, 255));
        Lb_nama.setText("ANGGOTA");

        Lbl_icon.setFont(new java.awt.Font("SansSerif", 1, 10)); // NOI18N
        Lbl_icon.setForeground(new java.awt.Color(255, 255, 255));
        Lbl_icon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Lbl_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/1.png"))); // NOI18N
        Lbl_icon.setPreferredSize(new java.awt.Dimension(50, 50));

        Lbl_jumlah.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        Lbl_jumlah.setForeground(new java.awt.Color(255, 255, 255));
        Lbl_jumlah.setText("10");

        javax.swing.GroupLayout CardanggotaLayout = new javax.swing.GroupLayout(Cardanggota);
        Cardanggota.setLayout(CardanggotaLayout);
        CardanggotaLayout.setHorizontalGroup(
            CardanggotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CardanggotaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Lb_nama)
                .addContainerGap(68, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CardanggotaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Lbl_icon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(CardanggotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(CardanggotaLayout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addComponent(Lbl_jumlah)
                    .addContainerGap(91, Short.MAX_VALUE)))
        );
        CardanggotaLayout.setVerticalGroup(
            CardanggotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CardanggotaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Lb_nama)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Lbl_icon, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(CardanggotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CardanggotaLayout.createSequentialGroup()
                    .addContainerGap(68, Short.MAX_VALUE)
                    .addComponent(Lbl_jumlah)
                    .addGap(10, 10, 10)))
        );

        Cardbuku.setBackground(new java.awt.Color(102, 51, 0));

        Lb_nama1.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        Lb_nama1.setForeground(new java.awt.Color(255, 255, 255));
        Lb_nama1.setText("BUKU");

        Lbl_icon1.setFont(new java.awt.Font("SansSerif", 1, 10)); // NOI18N
        Lbl_icon1.setForeground(new java.awt.Color(255, 255, 255));
        Lbl_icon1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Lbl_icon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/2.png"))); // NOI18N
        Lbl_icon1.setPreferredSize(new java.awt.Dimension(50, 50));

        Lbl_jumlah1.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        Lbl_jumlah1.setForeground(new java.awt.Color(255, 255, 255));
        Lbl_jumlah1.setText("10");

        javax.swing.GroupLayout CardbukuLayout = new javax.swing.GroupLayout(Cardbuku);
        Cardbuku.setLayout(CardbukuLayout);
        CardbukuLayout.setHorizontalGroup(
            CardbukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CardbukuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CardbukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(CardbukuLayout.createSequentialGroup()
                        .addComponent(Lb_nama1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(CardbukuLayout.createSequentialGroup()
                        .addComponent(Lbl_jumlah1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                        .addComponent(Lbl_icon1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        CardbukuLayout.setVerticalGroup(
            CardbukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CardbukuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Lb_nama1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CardbukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CardbukuLayout.createSequentialGroup()
                        .addComponent(Lbl_icon1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(29, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CardbukuLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Lbl_jumlah1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        Cardpeminjam.setBackground(new java.awt.Color(102, 51, 0));

        Lb_nama2.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        Lb_nama2.setForeground(new java.awt.Color(255, 255, 255));
        Lb_nama2.setText("PEMINJAMAN");

        Lbl_icon2.setFont(new java.awt.Font("SansSerif", 1, 10)); // NOI18N
        Lbl_icon2.setForeground(new java.awt.Color(255, 255, 255));
        Lbl_icon2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Lbl_icon2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/4.png"))); // NOI18N
        Lbl_icon2.setOpaque(true);
        Lbl_icon2.setPreferredSize(new java.awt.Dimension(50, 50));

        Lbl_jumlah2.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        Lbl_jumlah2.setForeground(new java.awt.Color(255, 255, 255));
        Lbl_jumlah2.setText("3");

        javax.swing.GroupLayout CardpeminjamLayout = new javax.swing.GroupLayout(Cardpeminjam);
        Cardpeminjam.setLayout(CardpeminjamLayout);
        CardpeminjamLayout.setHorizontalGroup(
            CardpeminjamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CardpeminjamLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Lb_nama2)
                .addContainerGap(80, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CardpeminjamLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Lbl_icon2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(CardpeminjamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(CardpeminjamLayout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addComponent(Lbl_jumlah2)
                    .addContainerGap(153, Short.MAX_VALUE)))
        );
        CardpeminjamLayout.setVerticalGroup(
            CardpeminjamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CardpeminjamLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Lb_nama2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Lbl_icon2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(CardpeminjamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CardpeminjamLayout.createSequentialGroup()
                    .addContainerGap(56, Short.MAX_VALUE)
                    .addComponent(Lbl_jumlah2)
                    .addGap(10, 10, 10)))
        );

        Cardpengembalian.setBackground(new java.awt.Color(102, 51, 0));

        Lb_nama3.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        Lb_nama3.setForeground(new java.awt.Color(255, 255, 255));
        Lb_nama3.setText("PENGEMBALIAN");

        Lbl_icon3.setFont(new java.awt.Font("SansSerif", 1, 10)); // NOI18N
        Lbl_icon3.setForeground(new java.awt.Color(255, 255, 255));
        Lbl_icon3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Lbl_icon3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/3.png"))); // NOI18N
        Lbl_icon3.setOpaque(true);
        Lbl_icon3.setPreferredSize(new java.awt.Dimension(50, 50));

        Lbl_jumlah3.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        Lbl_jumlah3.setForeground(new java.awt.Color(255, 255, 255));
        Lbl_jumlah3.setText("0");

        javax.swing.GroupLayout CardpengembalianLayout = new javax.swing.GroupLayout(Cardpengembalian);
        Cardpengembalian.setLayout(CardpengembalianLayout);
        CardpengembalianLayout.setHorizontalGroup(
            CardpengembalianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CardpengembalianLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Lb_nama3)
                .addContainerGap(51, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CardpengembalianLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Lbl_icon3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(CardpengembalianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(CardpengembalianLayout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addComponent(Lbl_jumlah3)
                    .addContainerGap(131, Short.MAX_VALUE)))
        );
        CardpengembalianLayout.setVerticalGroup(
            CardpengembalianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CardpengembalianLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Lb_nama3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Lbl_icon3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(CardpengembalianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CardpengembalianLayout.createSequentialGroup()
                    .addContainerGap(68, Short.MAX_VALUE)
                    .addComponent(Lbl_jumlah3)
                    .addGap(10, 10, 10)))
        );

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel1.setText("Riwayat Peminjam Buku");

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        jLabel2.setText("Dashboard");

        javax.swing.GroupLayout paneldasarLayout = new javax.swing.GroupLayout(paneldasar);
        paneldasar.setLayout(paneldasarLayout);
        paneldasarLayout.setHorizontalGroup(
            paneldasarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneldasarLayout.createSequentialGroup()
                .addGroup(paneldasarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, paneldasarLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(paneldasarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(paneldasarLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(paneldasarLayout.createSequentialGroup()
                                .addComponent(Cardanggota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Cardbuku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Cardpeminjam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Cardpengembalian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(8, 8, 8))))
                    .addGroup(paneldasarLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)))
                .addGap(17, 17, 17))
        );
        paneldasarLayout.setVerticalGroup(
            paneldasarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneldasarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(14, 14, 14)
                .addGroup(paneldasarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Cardbuku, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Cardpeminjam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Cardpengembalian, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Cardanggota, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(paneldasar, "card2");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Cardanggota;
    private javax.swing.JPanel Cardbuku;
    private javax.swing.JPanel Cardpeminjam;
    private javax.swing.JPanel Cardpengembalian;
    private javax.swing.JLabel Lb_nama;
    private javax.swing.JLabel Lb_nama1;
    private javax.swing.JLabel Lb_nama2;
    private javax.swing.JLabel Lb_nama3;
    private javax.swing.JLabel Lbl_icon;
    private javax.swing.JLabel Lbl_icon1;
    private javax.swing.JLabel Lbl_icon2;
    private javax.swing.JLabel Lbl_icon3;
    private javax.swing.JLabel Lbl_jumlah;
    private javax.swing.JLabel Lbl_jumlah1;
    private javax.swing.JLabel Lbl_jumlah2;
    private javax.swing.JLabel Lbl_jumlah3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel paneldasar;
    // End of variables declaration//GEN-END:variables
}
